### ISSUE TITLE
日記の新規作成画面で戻るボタンを押すと保存される

### ISSUE THREAD

**Issue by hyoshie** [yshima42/shirafu_life#56]
[IMO]
戻るボタンを押したときに保存されない方がいいと思うんですが、いかがでしょう？
日記を書くのをやめたい時にも保存されてしまいます。

_Originally posted by @hyoshie in https://github.com/yshima42/shirafu_life/pull/54#discussion_r1199693220_

**Comment by yshima42** [comment]
ごめんなさい、修正ミスです。修正します。
