### ISSUE TITLE
dropoutボタンを押すとrenderflexoverflow

### ISSUE THREAD

**Issue by hyoshie** [yshima42/shirafu_life#68]

**Comment by yshima42** [comment]
こちら修正方法2つ
- bottomSheetではなく日記のエントリーのように違う画面を下からせり上がってくるようにする
- ホーム画面をスクロール状態にする

【原因】
- bottomSheetを出して、キーボードが出された時に、ホーム画面側がキーボードとかぶらないように縮小されるようになっている

**Comment by yshima42** [comment]
現在、#86 で表示を減らしたためでなくなっているけど根本解決はまだできていない。ホーム画面に要素増やしたり、画面の小さいスマホを使えばオーバーフローは起きる可能性あり。
